# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Voluny' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Voluny
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'GooglePlaces'
  pod 'Cosmos'
  pod 'FirebaseUI/Storage', '~> 4.0'
  pod 'SDWebImage'
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 4.5'
  pod 'IQKeyboardManagerSwift'

end
